### ISSUE TITLE
Synchronous rendering

### ISSUE THREAD

**Issue by agarzola** [jstransformers/jstransformer-autoprefixer#10]
Hi! I’m trying to do something like this in pug:

```
style
  include:autoprefixer:stylus(compress=true) path/to/critical/styles.styl
```

I get the following error in the console:

```
Error in plugin 'gulp-pug'
Message:
    The Transform "autoprefixer" does not support rendering synchronously.
```

This template is being rendered server-side, not in the browser. I’m not sure if I’m doing something wrong in chaining filters in pug or there’s a legitimate issue with `jstransformer-autoprefixer`, so I’m reporting it here in hopes someone can point me in the right direction. What would be the best way for me to achieve what I’m trying to do above?

**Comment by RobLoach** [comment]
It looks like Pug doesn't support asyncronous JSTransformer includes?

@TimothyGu may be able to chip in a bit.

**Comment by TimothyGu** [comment]
Pug doesn't support async filters, that is correct.

But PostCSS and Autoprefixer do.

And thus, fixed in 1.1.0.

**Comment by TimothyGu** [comment]
Check https://tonicdev.com/timothygu/5795daa2c9ce751400ffd11c!

**Comment by agarzola** [comment]
1.1.0 fixes it, @TimothyGu! Thanks a bunch!

**Comment by RobLoach** [comment]
Nicely done, @TimothyGu. See your PostCSS fixes too.
