### ISSUE TITLE
Published version is broken/out-of-date

### ISSUE THREAD

**Issue by bignell** [jstransformers/jstransformer-autoprefixer#3]
The [jstransformer-autoprefixer](https://www.npmjs.com/package/jstransformer-autoprefixer) npm package appears to be sync'd to an incomplete older version—it doesn't list any dependencies (like, say, autoprefixer itself :wink:).

Installing via the Github tarball yields a working version.

I think it's as simple as bumping the version number—the current (Github) version is the same as the registry version (0.0.1), and the registry doesn't allow for [identical version numbers](http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f).

**Comment by TimothyGu** [comment]
See #2. Nobody except for @tunnckoCore has npm owner permissions.

**Comment by ForbesLindesay** [comment]
I've just published v1.0.1, which is fully up to date.
